### ISSUE TITLE
Sorry, the link has expired.

### ISSUE THREAD

**Issue by 943fansi** [danelee2601/supervised-FCN#1]
`You can download it from [here](https://studntnu-my.sharepoint.com/:u:/g/personal/daesool_ntnu_no/EUVHWAlJRrZBnCZMAOdTR-cB3m_LP7Q10Y78meuzUAuIBQ?e=h9aGhi)`

Could you please update the link above?

**Comment by danelee2601** [comment]
sorry about the late reply. I forgot to update it before, thanks for the check :)
I've just updated it and it should work now.
